class AddAutoGeneratedToMachines < ActiveRecord::Migration
  def change
    add_column :machines, :auto_generated, :boolean, default: false
    add_column :products, :auto_generated, :boolean, default: false
  end
end
